### ISSUE TITLE
two way binding

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/bind-to#3]
http://jsbin.com/wejab/3/edit

changes to textarea should update input field.

similarly, it shouldn't matter if I do $('p').bindTo('input') or $('input').bindTo('p')

**Comment by Antonio-Laguna** [comment]
What happens if both elements have value?

**Comment by Antonio-Laguna** [comment]
I can't see the second comment you do as dangerous. For example if we bind two things to each other, as soon as one event fires it will fire again on the other one, leading to infinite loop of events

**Comment by jgallen23** [comment]
Sure, but that's the devs fault if they bind things circularly, right?  All I was saying is since we are doing two way data binding it shouldn't matter which element I call it on first. Right now I have to bind the input as the bindTo(input) vs $(input)

**Comment by Antonio-Laguna** [comment]
Well let me share my thoughts on this.

So, in order to achieve this, we would need to bind to both events on change, let's say it's two inputs, so we would bind internally to `keyup` on both so no matter which one is updated, the other one is updated too. That's fine.

However, if we would like to have a cascading effect like the one you mention on this issue, we would need to trigger that same event so it fires in case it's bound to another element. So, as soon as you fire this event, the other element would catch it, and start the flow again, in a loop.

Maybe I'm missing something. What do you think?

**Comment by jgallen23** [comment]
I'm not sure what you mean by cascading effect.  Are you just referring to binding multiple elements together?

**Comment by Antonio-Laguna** [comment]
Well, if you bind a `p` to an `input` and that `input` to a `textarea` (for example) you'd like the P value to be passed to the textarea, right? That's the cascade.

**Comment by jgallen23** [comment]
for now, lets not worry about cascading.  Just two way where I bind an input to a text area, if I change either, they both get updated.  My biggest issue right now is not knowing which order it should be.  `$('p').bindTo('input')` or `$('input').bindTo('p')`.  The two way binding should solve for that.

**Comment by jgallen23** [comment]
I wonder if we need to, internally, always create a model (`$.bindTo(elem)`) and be able to add additional elements to it and then it knows if something changes, to not trigger updates and cause an infinite loop.  Need to think through this some more

**Comment by jgallen23** [comment]
looks good!

**Comment by jgallen23** [comment]
can you merge this into master, I was getting merge conflicts
